add cli commands for bitcoin-cli

diff --git a/citadel-dev b/citadel-dev
--- a/citadel-dev
+++ b/citadel-dev
@@ -22,6 +22,8 @@ Commands:
     logs                    Stream Citadel logs
     run <command>           Run a command inside the development VM
     ssh                     Get an SSH session inside the development VM
+    bitcoin-cli <command>   Run bitcoin-cli with arguments
+    auto-mine <seconds>     Generate a block continuously
 EOF
 }
 
@@ -219,6 +221,29 @@ if [[ "$command" = "run" ]]; then
     exit 1
   fi
   run_in_vm "$2"
+  exit
+fi
+
+# Run bitcoin-cli with arguments
+if [[ "$command" = "bitcoin-cli" ]]; then
+  check_citadel_dev_environment
+  if [ -z ${2+x} ]; then
+    args=""
+  else
+    args="${@:2}"
+  fi
+  run_in_vm "docker exec -it bitcoin bitcoin-cli ${args}"
+  exit
+fi
+
+# Generate a block continuously
+if [[ "$command" = "auto-mine" ]]; then
+  check_citadel_dev_environment
+  if [ -z ${2+x} ]; then
+    echo "Missing argument: Specify an interval in seconds"
+    exit 1
+  fi
+  run_in_vm "while true; do docker exec -it bitcoin bitcoin-cli -generate 1; sleep $2; done"
   exit
 fi
 
